import React from 'react';
import { motion } from 'framer-motion';
import { Lightbulb, AlertTriangle, Info, CheckCircle2 } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';

const insights = [
  {
    type: "critical",
    title: "Reduce Fast Charging Frequency",
    description: "Our model detects accelerated anode degradation correlated with daily 65W+ fast charging. Switch to standard 15W charging overnight to extend lifespan by estimated 12%.",
    icon: AlertTriangle,
    color: "text-red-500",
    bg: "bg-red-500/10",
    border: "border-red-500/20"
  },
  {
    type: "warning",
    title: "Avoid Deep Discharges",
    description: "You frequently let the battery drop below 10%. Lithium-ion cells experience significant stress at low voltages. Try to plug in at 20% to reduce cycle strain.",
    icon: Info,
    color: "text-orange-500",
    bg: "bg-orange-500/10",
    border: "border-orange-500/20"
  },
  {
    type: "tip",
    title: "Thermal Management Optimal",
    description: "Average operating temperature is 28°C, well within the optimal range. Keep avoiding direct sunlight exposure to maintain this healthy baseline.",
    icon: CheckCircle2,
    color: "text-emerald-500",
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/20"
  },
  {
    type: "warning",
    title: "Overnight Charging Stress",
    description: "The device sits at 100% state-of-charge (SOC) for an average of 6 hours a night. Enable 'Optimized Battery Charging' in OS settings to hold charge at 80% until morning.",
    icon: Info,
    color: "text-orange-500",
    bg: "bg-orange-500/10",
    border: "border-orange-500/20"
  },
  {
    type: "tip",
    title: "Software Updates",
    description: "Ensure device firmware is up to date. Recent updates often contain revised Power Management IC (PMIC) algorithms that improve efficiency.",
    icon: CheckCircle2,
    color: "text-emerald-500",
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/20"
  },
  {
    type: "tip",
    title: "Use Original Accessories",
    description: "Third-party chargers may lack proper communication protocols, leading to unregulated current spikes. Stick to OEM adapters for critical devices.",
    icon: CheckCircle2,
    color: "text-emerald-500",
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/20"
  }
];

export default function Insights() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-5xl">
      <div className="text-center mb-12">
        <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary/10 text-primary mb-6">
          <Lightbulb size={32} />
        </div>
        <h1 className="text-3xl md:text-5xl font-bold mb-4">AI <span className="text-gradient">Insights</span></h1>
        <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
          Actionable recommendations generated by our machine learning model based on your specific usage patterns.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {insights.map((insight, idx) => {
          const Icon = insight.icon;
          return (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.1 }}
            >
              <Card className={`h-full border ${insight.border} bg-card/40 hover:bg-card/60 transition-colors`}>
                <CardContent className="p-6">
                  <div className="flex items-start gap-4">
                    <div className={`p-3 rounded-lg ${insight.bg} ${insight.color} shrink-0`}>
                      <Icon size={24} />
                    </div>
                    <div>
                      <div className="flex items-center gap-2 mb-2">
                        <h3 className="font-bold text-lg">{insight.title}</h3>
                        <span className={`text-[10px] uppercase font-bold px-2 py-0.5 rounded-full border ${insight.border} ${insight.color}`}>
                          {insight.type}
                        </span>
                      </div>
                      <p className="text-muted-foreground text-sm leading-relaxed">
                        {insight.description}
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}